[book]
authors = ["Radenz"]
language = "en"
multilingual = false
src = "."
title = "IF3170 Intelegensi Buatan"

[preprocessor.transform]
command = "python ../shared/transform.py"

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "2.0.0"

[output.html]
mathjax-support = true
additional-css = ['../shared/admonish.css']
